[platformio]
default_envs = generic
src_dir = .

[common]
platform = espressif32@6.9.0
framework = arduino
board = esp32-c3-devkitm-1
upload_speed = 460800
monitor_speed = 115200
build_flags =
	-DCORE_DEBUG_LEVEL=3
lib_deps =
	bblanchon/ArduinoJson@^7
	ESP32Async/AsyncTCP@^3.3.7
	ESP32Async/ESPAsyncWebServer@^3.6.0
	https://github.com/256dpi/arduino-mqtt
	https://github.com/miguelbalboa/rfid#ea7ee3f3daafd46d0c5b8438ba41147c384a1f0d
	matjack1/Wiegand Protocol Library for Arduino - for esp-rfid@^1.1.1
	Time@1.5
	Bounce2@2.52

[env:generic]
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
lib_deps = ${common.lib_deps}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}

[env:debug]
platform = ${common.platform}
framework = ${common.framework}
board = ${common.board}
lib_deps = ${common.lib_deps}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}
	-DDEBUG
